name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging

jobs:
  tests:
    # permissions:
    #   id-token: write
    #   contents: read

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@master
      #   with:
      #     aws-region: us-east-1
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: npm install
        run: npm ci
      - name: npm test
        run: npm run test-slow
